services:
  postgres:
    image: postgres:16-alpine
    container_name: crm-app-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crm_db
    volumes:
      - crm_pgdata:/var/lib/postgresql/data

volumes:
  crm_pgdata:
